language: cpp
dist: focal
compiler: gcc

addons:
  apt:
    update: true
    packages:
      - cmake
      - lcov
      - ruby
      - ruby-dev

before_script:
  - git submodule update --init --recursive

script:
  - cmake -H. -B_build -DBUILD_TESTS=ON -DENABLE_COVERAGE=ON -DCMAKE_CXX_FLAGS="-Wno-error=maybe-uninitialized"
  - cmake --build _build
  - cmake --build _build --target test -- ARGS=--verbose
  - ./_build/check

after_success:
  - lcov --capture --directory _build/banking --output-file coverage.info --ignore-errors mismatch,mismatch
  - lcov --remove coverage.info '/usr/*' '*/third-party/*' '*/tests/*' --output-file coverage.info --ignore-errors unused
  - lcov --list coverage.info
  - gem install coveralls-lcov
  - coveralls-lcov coverage.info
